import type { Metadata } from 'next'


export const metadata: Metadata = {
  title: 'Actividades',
  description: 'Generated by create BBR',
}

export default function ActLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
   <div>

        {children}
   </div>
  )
}



